// Generated by scripts/build-maptivate.mjs from data/Maptivate-View–Access-Map.csv
// Re-run that script when the CSV changes. Do not edit by hand.

export type Venue = {
  id: string
  title: string
  lga: string
  address: string
  lat: number
  lng: number
  buildingType: string
  access: string[]
  accessibilityNotes: string
  accessibilitySummary: string
  carersInfo: string
}

export const LGAS: string[] = [
  "City of Maribyrnong",
  "City of Melbourne",
  "City of Port Phillip",
  "City of Stonnington",
  "City of Yarra"
]

export const VENUES: Venue[] = [
  {
    "id": "anz-gothic-bank-museum-and-verdon-chambers",
    "title": "ANZ Gothic Bank Museum and Verdon Chambers",
    "lga": "City of Melbourne",
    "address": "388 Collins St, Melbourne VIC 3000",
    "lat": -37.81646609995862,
    "lng": 144.96175149835,
    "buildingType": "Heritage",
    "access": [
      "Ramp or level (step free) entry",
      "Lift access to all public levels",
      "Accessible bathrooms"
    ],
    "accessibilityNotes": "The Gothic Banking Museum and Verdon Chambers has accessibility access.",
    "accessibilitySummary": "",
    "carersInfo": ""
  },
  {
    "id": "parliament-of-victoria",
    "title": "Parliament of Victoria",
    "lga": "City of Melbourne",
    "address": "Parliament House, Spring St, East Melbourne VIC 3002",
    "lat": -37.81087443820236,
    "lng": 144.973808535582,
    "buildingType": "Government",
    "access": [
      "Ramp or level (step free) entry",
      "Lift access to all public levels",
      "Accessible bathrooms",
      "All-gender bathrooms",
      "Parent's Room",
      "Assistive listening/hearing loop",
      "Quiet or sensory rooms",
      "Social Stories"
    ],
    "accessibilityNotes": "People with a mobility or physical disability can access Parliament House through the side entrance on Spring street or the rear entrance on Macarthur Street.\nAccessible toilets are located on the ground level and level one.\nAuslan videos are provided at points of interest on our public tours by scanning QR codes with your smartphone.  \nTwo social stories are available to accompany a visit to Parliament House. These have been designed for visitors who are neurodiverse who may like to read them in preparation for their visit. One is intended for readers of all ages, the other focuses on the experience of a school visit to parliament house.",
    "accessibilitySummary": "",
    "carersInfo": ""
  },
  {
    "id": "queen-victoria-women-s-centre",
    "title": "Queen Victoria Women's Centre",
    "lga": "City of Melbourne",
    "address": "210 Lonsdale St, Melbourne VIC 3000",
    "lat": -37.81058391833173,
    "lng": 144.9658324558239,
    "buildingType": "Cultural",
    "access": [
      "Ramp or level (step free) entry",
      "Lift access to all public levels",
      "Accessible bathrooms",
      "All-gender bathrooms",
      "Level access tram stop",
      "Quiet or sensory rooms",
      "Assistance animals welcome",
      "All ages"
    ],
    "accessibilityNotes": "Visitors with mobility aids are welcome to use the side ramp on Shilling Lane or the platform lift next to the QVWC shop on the QV courtyard side to access automated doors at the rear of the building. Inside, there is a passenger lift for all floors, and platform lifts and mobile ramps for short steps.",
    "accessibilitySummary": "",
    "carersInfo": ""
  },
  {
    "id": "victorian-archives-centre",
    "title": "Victorian Archives Centre",
    "lga": "City of Melbourne",
    "address": "99 Shiel St, North Melbourne VIC 3051",
    "lat": -37.79628396381408,
    "lng": 144.9422071865079,
    "buildingType": "Government",
    "access": [
      "Ramp or level (step free) entry",
      "Lift access to all public levels",
      "Accessible bathrooms",
      "All-gender bathrooms",
      "Accessible parking",
      "Level access tram stop",
      "Assistance animals welcome",
      "Auslan interpreter available on request"
    ],
    "accessibilityNotes": "If you require an Auslan interpreter, please email media@prov.vic.gov.au by 9am, Friday 10 July, so an external contractor can be booked.",
    "accessibilitySummary": "",
    "carersInfo": ""
  },
  {
    "id": "australian-centre-for-contemporary-art-acca",
    "title": "Australian Centre for Contemporary Art (ACCA)",
    "lga": "City of Melbourne",
    "address": "Australian Centre for Contemporary Art (ACCA), 111 Sturt St, Southbank VIC 3006",
    "lat": -37.826727635469645,
    "lng": 144.96658553735622,
    "buildingType": "Cultural",
    "access": [
      "Ramp or level (step free) entry",
      "Accessible bathrooms",
      "All-gender bathrooms",
      "Accessible parking",
      "Auslan interpreter available on request",
      "Social Stories",
      "Assistance animals welcome",
      "All ages"
    ],
    "accessibilityNotes": "",
    "accessibilitySummary": "",
    "carersInfo": ""
  },
  {
    "id": "koorie-heritage-trust-first-peoples-cultures-and-songlines-i",
    "title": "Koorie Heritage Trust: First Peoples Cultures and Songlines in Art, Design and Architecture",
    "lga": "City of Melbourne",
    "address": "Birrarung Building, Fed Square, Cnr Swanston & Flinders St, Melbourne VIC 3000",
    "lat": -37.8179475041245,
    "lng": 144.96913379325395,
    "buildingType": "Cultural",
    "access": [
      "Lift access to all public levels",
      "Accessible bathrooms",
      "All-gender bathrooms",
      "Level access tram stop",
      "All ages",
      "Assistance animals welcome",
      "Ramp or level (step free) entry",
      "Accessible parking"
    ],
    "accessibilityNotes": "Lift access available to all floors of the building. Wheelchair accessible bathrooms available on all levels.",
    "accessibilitySummary": "",
    "carersInfo": ""
  },
  {
    "id": "melbourne-electronic-sound-studio-mess",
    "title": "Melbourne Electronic Sound Studio (MESS)",
    "lga": "City of Melbourne",
    "address": "The Atrium, Fed Square, Melbourne VIC 3000",
    "lat": -37.81752322761892,
    "lng": 144.969410464418,
    "buildingType": "Cultural",
    "access": [
      "Ramp or level (step free) entry",
      "Accessible bathrooms",
      "All-gender bathrooms",
      "Parent's Room",
      "Accessible parking",
      "Assistance animals welcome",
      "All ages"
    ],
    "accessibilityNotes": "There are accessible public toilets and baby-change facilities located in The Atrium, next to MESS. For more info, find accessibility information available on MESS website.",
    "accessibilitySummary": "",
    "carersInfo": ""
  },
  {
    "id": "melbourne-recital-centre",
    "title": "Melbourne Recital Centre",
    "lga": "City of Melbourne",
    "address": "31 Sturt St, Southbank VIC 3006",
    "lat": -37.823519861637216,
    "lng": 144.9677105883516,
    "buildingType": "Cultural",
    "access": [
      "Ramp or level (step free) entry",
      "Lift access to all public levels",
      "Accessible bathrooms",
      "All-gender bathrooms",
      "Level access tram stop",
      "Assistive listening/hearing loop",
      "Social Stories",
      "Assistance animals welcome",
      "All ages"
    ],
    "accessibilityNotes": "Public tours presented as part of Open House Melbourne require patrons to be comfortable with walking throughout the building in both public and backstage areas. These areas are designed with accessibility in mind, however there may be times where lift or escalator access is unavailable.",
    "accessibilitySummary": "",
    "carersInfo": ""
  },
  {
    "id": "shrine-of-remembrance-stories-in-stone-and-landscape",
    "title": "Shrine of Remembrance: Stories in Stone and Landscape",
    "lga": "City of Melbourne",
    "address": "Shrine of Remembrance, 100 Birdwood Ave, Melbourne VIC 3001",
    "lat": -37.830135071719766,
    "lng": 144.97344262883595,
    "buildingType": "Cultural",
    "access": [
      "Ramp or level (step free) entry",
      "Lift access to all public levels",
      "Accessible bathrooms",
      "All-gender bathrooms"
    ],
    "accessibilityNotes": "Access to the balcony is by stairs only.\nThere is lift access to all other parts of the building.",
    "accessibilitySummary": "",
    "carersInfo": ""
  },
  {
    "id": "la-mama-theatre",
    "title": "La Mama Theatre",
    "lga": "City of Melbourne",
    "address": "205 Faraday St, Carlton VIC 3053",
    "lat": -37.798789,
    "lng": 144.96779,
    "buildingType": "Cultural",
    "access": [
      "Ramp or level (step free) entry",
      "Lift access to all public levels",
      "Accessible bathrooms",
      "All-gender bathrooms",
      "Quiet or sensory rooms",
      "Social Stories",
      "Assistance animals welcome",
      "All ages"
    ],
    "accessibilityNotes": "There is a lift at the entrance of the theatre as alternative to six stairs; and lift available from ground floor to first floor level for backstage tour. Accessible toilet available on ground floor. Closest accessible parking is on Faraday Street, near Drummond Street.",
    "accessibilitySummary": "",
    "carersInfo": ""
  },
  {
    "id": "trades-hall-and-literary-institute",
    "title": "Trades Hall and Literary Institute",
    "lga": "City of Melbourne",
    "address": "54 Victoria St, Carlton South VIC 3053",
    "lat": -37.806094881015305,
    "lng": 144.96636170307175,
    "buildingType": "Heritage",
    "access": [
      "Lift access to all public levels",
      "Accessible bathrooms",
      "All-gender bathrooms",
      "Parent's Room",
      "Assistance animals welcome",
      "All ages"
    ],
    "accessibilityNotes": "Accessible toilets available on every floor. Disability lift available. There are two accessible car parks on the Lygon St side of the building.",
    "accessibilitySummary": "",
    "carersInfo": ""
  },
  {
    "id": "melbourne-quarter-grand-opening-tour",
    "title": "Melbourne Quarter: Grand Opening Tour",
    "lga": "City of Melbourne",
    "address": "695 Collins St, Docklands VIC 3008",
    "lat": -37.81990889210784,
    "lng": 144.951886217791,
    "buildingType": "Commercial",
    "access": [
      "Lift access to all public levels",
      "Accessible bathrooms",
      "Level access tram stop"
    ],
    "accessibilityNotes": "Lifts available for all levels open to the public, located outside Southern Cross Station",
    "accessibilitySummary": "",
    "carersInfo": ""
  },
  {
    "id": "melbourne-quarter-s-public-art",
    "title": "Melbourne Quarter's Public Art",
    "lga": "City of Melbourne",
    "address": "695 Collins St, Docklands VIC 3008",
    "lat": -37.81991312968671,
    "lng": 144.951880853373,
    "buildingType": "Commercial",
    "access": [
      "Lift access to all public levels",
      "Accessible bathrooms",
      "Level access tram stop"
    ],
    "accessibilityNotes": "Lifts available for all levels open to the public, located outside Southern Cross Station",
    "accessibilitySummary": "",
    "carersInfo": ""
  },
  {
    "id": "footscray-community-arts",
    "title": "Footscray Community Arts",
    "lga": "City of Maribyrnong",
    "address": "45 Moreland St, Footscray VIC 3011",
    "lat": -37.80315823523451,
    "lng": 144.9069300625991,
    "buildingType": "Performing or visual arts",
    "access": [
      "Ramp or level (step free) entry",
      "Accessible bathrooms",
      "All-gender bathrooms",
      "Auslan interpreter available on request",
      "Quiet or sensory rooms",
      "Assistance animals welcome",
      "Accessible parking",
      "Other"
    ],
    "accessibilityNotes": "Henderson House is not fully wheelchair accessible.",
    "accessibilitySummary": "",
    "carersInfo": ""
  },
  {
    "id": "australian-tapestry-workshop",
    "title": "Australian Tapestry Workshop",
    "lga": "City of Port Phillip",
    "address": "262-266 Park St, South Melbourne VIC 3205",
    "lat": -37.83520026884749,
    "lng": 144.9604447490741,
    "buildingType": "Cultural",
    "access": [
      "Ramp or level (step free) entry",
      "Accessible bathrooms",
      "All-gender bathrooms",
      "Accessible parking",
      "Assistance animals welcome"
    ],
    "accessibilityNotes": "There is ramp access to the shop, exhibitions and views onto the workshop floor. Mezzanine level is not wheelchair accessible. \nThere is an accessible parking space in front, and accessible bathroom available.",
    "accessibilitySummary": "",
    "carersInfo": ""
  },
  {
    "id": "jewish-museum-australia-guided-tours",
    "title": "Jewish Museum Australia Guided Tours",
    "lga": "City of Port Phillip",
    "address": "26 Alma Rd, St Kilda VIC 3182",
    "lat": -37.859902825614384,
    "lng": 144.9855366266577,
    "buildingType": "Cultural",
    "access": [
      "Ramp or level (step free) entry",
      "Lift access to all public levels",
      "Accessible bathrooms",
      "All-gender bathrooms",
      "Social Stories",
      "All ages"
    ],
    "accessibilityNotes": "We are committed to providing opportunities for all members of the community to experience our Museum. We have worked to ensure our exhibitions, events and education programs are as accessible as possible for people with restricted mobility. Yet, due to the age and restrictions that exist within our building, some parts of our venue have limited access. These areas include our front entrance and lift. The Museum has disability-access toilets on the ground floor.\nWhen visiting the Museum, we ask you to please take into account the following:\nBuilding Access\nThe front entrance of the Museum has steps. Visitors with restricted mobility, including those using wheelchairs, can access the building via our schools’ entrance at rear. Please ring the Museum ahead of your visit and we can assist to organise access.\n\nLift\nOur passenger lift has the following dimensions: (approx.) 900mm (wide) x 1200mm (deep). We appreciate the lift may not fit all sizes of wheelchairs and apologise in advance for any inconvenience caused. Should there be any difficulty in accessing lift control buttons or any aspect of our accessibility, our team are always nearby to assist.\n\nFuture Plans\nThe Museum is currently planning an upgrade to our forecourt, including a new wheelchair accessible ramp. We place great importance on improving our accessibility so that all members of the community can share in the Australian Jewish story.\nIf you would like to discuss the accessibility of our venue, please contact a member of our Experience and Facilities team on +61 3 8534 3600.",
    "accessibilitySummary": "",
    "carersInfo": ""
  },
  {
    "id": "victorian-pride-centre",
    "title": "Victorian Pride Centre",
    "lga": "City of Port Phillip",
    "address": "79-81 Fitzroy St, St Kilda VIC 3182",
    "lat": -37.86053530179165,
    "lng": 144.9763448,
    "buildingType": "Mixed-use",
    "access": [
      "Ramp or level (step free) entry",
      "Lift access to all public levels",
      "Accessible bathrooms",
      "All-gender bathrooms",
      "Level access tram stop",
      "Assistive listening/hearing loop",
      "Quiet or sensory rooms",
      "Assistance animals welcome",
      "All ages"
    ],
    "accessibilityNotes": "No on-site visitor parking available",
    "accessibilitySummary": "",
    "carersInfo": ""
  },
  {
    "id": "abbotsford-convent",
    "title": "Abbotsford Convent",
    "lga": "City of Yarra",
    "address": "1 St Heliers St, Abbotsford VIC 3067",
    "lat": -37.80188173449213,
    "lng": 145.00394400185178,
    "buildingType": "Cultural",
    "access": [
      "Ramp or level (step free) entry",
      "Accessible bathrooms",
      "All-gender bathrooms",
      "Parent's Room",
      "Accessible parking",
      "Social Stories",
      "Assistance animals welcome",
      "All ages"
    ],
    "accessibilityNotes": "Being a heritage site, the Abbotsford Convent has uneven pavement and stairs throughout.",
    "accessibilitySummary": "",
    "carersInfo": ""
  },
  {
    "id": "fitzroy-neighbourhood-house",
    "title": "Fitzroy Neighbourhood House",
    "lga": "City of Yarra",
    "address": "140 Brunswick St, Atherton Gardens Housing Estate, Fitzroy, Melbourne VIC 3065",
    "lat": -37.803153348650305,
    "lng": 144.978005471164,
    "buildingType": "Education",
    "access": [
      "Ramp or level (step free) entry",
      "Accessible bathrooms",
      "All-gender bathrooms",
      "Assistance animals welcome",
      "All ages"
    ],
    "accessibilityNotes": "Public transport via the 11 & 86 tram will take visitors to the front of FNH, street parking is limited but bicycle parking plenty. Step free access and path of travel from Brunswick Street is provided. A reminder for all that the space is located on the ground floor of the Atherton Gardens Estate and as such is a busy intersection of public and private space.",
    "accessibilitySummary": "",
    "carersInfo": ""
  },
  {
    "id": "today-a-sustainable-design-studio",
    "title": "Today: A Sustainable Design Studio",
    "lga": "City of Yarra",
    "address": "8/54 Wellington St, Collingwood VIC 3066",
    "lat": -37.80692467565223,
    "lng": 144.98626216441798,
    "buildingType": "Workplace",
    "access": [
      "Ramp or level (step free) entry",
      "Lift access to all public levels",
      "Accessible bathrooms",
      "All-gender bathrooms",
      "Parent's Room",
      "Quiet or sensory rooms",
      "Social Stories",
      "All ages",
      "Sensory maps"
    ],
    "accessibilityNotes": "Meet at bottom stairwell to take the lifts.\nSocial Stories available.",
    "accessibilitySummary": "",
    "carersInfo": ""
  },
  {
    "id": "nica-the-joys-of-circus",
    "title": "NICA: The Joys of Circus",
    "lga": "City of Stonnington",
    "address": "39-59 Green St, Prahran VIC 3181",
    "lat": -37.85264700215921,
    "lng": 144.99167852698508,
    "buildingType": "Performing or visual arts",
    "access": [
      "Ramp or level (step free) entry",
      "Accessible bathrooms",
      "All-gender bathrooms",
      "Assistance animals welcome",
      "All ages"
    ],
    "accessibilityNotes": "Wheelchair/mobility accessible, all entrances are at ground level.\nToilets, change rooms and gender neutral toilets are available in the NICA main entrance foyer.\nHard, non-carpeted flooring throughout.\nSupport animals  are allowed.\nFree drinking water provided.\nIf I have specific access needs or questions, I can talk to NICA Recreation on 1300 006422 or email receation@nica.com.au",
    "accessibilitySummary": "",
    "carersInfo": ""
  }
]
